// <auto-generated />
using System;
using EcoLessonAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoLessonAPI.Migrations
{
    [DbContext(typeof(EcoLessonDbContext))]
    partial class EcoLessonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoLessonAPI.Models.Certificado", b =>
                {
                    b.Property<string>("IdCertificado")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ID_CERTIFICADO");

                    b.Property<string>("CodigoValidacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CODIGO_VALIDACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("DtEmissao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_EMISSAO");

                    b.Property<decimal>("IdCurso")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_CURSO");

                    b.Property<decimal>("IdUsuario")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdCertificado");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("T_CERTIFICADO", (string)null);
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Curso", b =>
                {
                    b.Property<decimal>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_CURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdCurso"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME_CURSO");

                    b.Property<decimal>("QtHoras")
                        .HasColumnType("NUMBER")
                        .HasColumnName("QT_HORAS");

                    b.HasKey("IdCurso");

                    b.ToTable("T_CURSO", (string)null);
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Empresa", b =>
                {
                    b.Property<decimal>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_EMPRESA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("EmailEmpresa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL_EMPRESA");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("T_EMPRESA", (string)null);
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Usuario", b =>
                {
                    b.Property<decimal>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdUsuario"));

                    b.Property<DateTime>("Cadastro")
                        .HasColumnType("DATE")
                        .HasColumnName("CADASTRO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("EmailUsuario")
                        .IsUnique();

                    b.ToTable("T_USUARIOS", (string)null);
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Vaga", b =>
                {
                    b.Property<decimal>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_VAGA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdVaga"));

                    b.Property<string>("DescricaoVaga")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRICAO_VAGA");

                    b.Property<DateTime>("DtPublicacao")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_PUBLICACAO");

                    b.Property<decimal>("IdEmpresa")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("NomeVaga")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NOME_VAGA");

                    b.Property<decimal>("Salario")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("SALARIO");

                    b.HasKey("IdVaga");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("T_VAGA", (string)null);
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Certificado", b =>
                {
                    b.HasOne("EcoLessonAPI.Models.Curso", "Curso")
                        .WithMany("Certificados")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoLessonAPI.Models.Usuario", "Usuario")
                        .WithMany("Certificados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Vaga", b =>
                {
                    b.HasOne("EcoLessonAPI.Models.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Curso", b =>
                {
                    b.Navigation("Certificados");
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("EcoLessonAPI.Models.Usuario", b =>
                {
                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
